# Generated by Django 5.0.1 on 2024-01-05 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool_disease', models.BooleanField(default=False)),
                ('disease', models.CharField(choices=[('VM', 'Varroa mite'), ('AW', 'Acarapis woodi')], max_length=2)),
                ('date_of_infection', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Beeyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beeyards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('WAIT', 'Waiting'), ('DEST', 'Destroyed')], max_length=4)),
                ('date_of_status_modification', models.DateField()),
                ('queen_date_of_birth', models.DateField()),
                ('varieties', models.CharField(choices=[('BF', 'Buckfast'), ('BB', 'Apis mellifera mellifera '), ('IB', 'Apis mellifera ligustica')], max_length=2)),
                ('beeyard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hives', to='api.beeyard')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='api.hive')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateField()),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='api.hive')),
            ],
        ),
    ]
