# Generated by Django 5.0.1 on 2024-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disease_hive_hive_registration_treatment_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Waiting', 'Waiting'), ('Destroyed', 'Destroyed')], max_length=15),
        ),
        migrations.AlterField(
            model_name='hive',
            name='varieties',
            field=models.CharField(choices=[('Buckfast', 'Buckfast'), ('Apis mellifera mellifera', 'Apis mellifera mellifera '), ('Apis mellifera ligustica', 'Apis mellifera ligustica')], max_length=50),
        ),
    ]
