# Generated by Django 5.0.1 on 2024-01-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hive_status_alter_hive_varieties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease',
            field=models.CharField(choices=[('Varroa mite', 'Varroa mite'), ('Acarapis woodi', 'Acarapis woodi')], max_length=15),
        ),
    ]
