# Generated by Django 5.0.1 on 2024-01-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_disease_disease'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beekeeper',
        ),
    ]
